# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

#Sistema Operacional
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
      # Compilando o projeto
    - name: Compilar o projeto
      run: javac -cp src Main.java
           javac -cp src Teste.java

      # Executando o projeto 
    - name: Executar o projeto
      run: java -cp .Teste
      
      #Exemplo 1 para versionamento
    - name: Gerando Versão
      run: echo ${{ github.run_number }}
      #colocar para utilizar o script do docker e colocar na tag latest
      
      #Exemplo 2 para versionamento
          
